CREATE DATABASE @db DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;

USE @db;

CREATE TABLE @tpusers (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(40) COLLATE utf8_bin UNIQUE NOT NULL DEFAULT 'badname',
  PASSWORD varchar(80) COLLATE utf8_bin NOT NULL DEFAULT 'e10adc3949ba59abbe56e057f20f883e',
  MAIL varchar(255) UNIQUE NOT NULL,
  DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SESSION varchar(32) COLLATE utf8_bin NOT NULL DEFAULT 0,
  CSS varchar(40) COLLATE utf8_bin NOT NULL DEFAULT 'Zulaijen',
  SAFE tinyint(4) NOT NULL DEFAULT 2,
  UPLOADS bigint(20) DEFAULT 0,
  BAN datetime DEFAULT '1900-01-01 00:00:00',
  BANCOUNT tinyint(4) unsigned DEFAULT 0,
  ISADMIN boolean NOT NULL DEFAULT FALSE,
  ISMOD boolean NOT NULL DEFAULT FALSE,
  IP varchar(15) NOT NULL,
  PROXY varchar(15) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO @tpusers (NAME,PASSWORD,MAIL,DATE,LAST,SESSION,CSS,SAFE,UPLOADS,BAN,BANCOUNT,ISADMIN,ISMOD,IP,PROXY) VALUES ('admin','e10adc3949ba59abbe56e057f20f883e', 'admin@host.com', NOW(),NOW(),'0','Zulaijen',0,0,'1900-01-01 00:00:00', 0, TRUE, TRUE, '127.0.0.1', '0.0.0.0');

CREATE TABLE @tpimages (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  EXTENSION varchar(3) COLLATE utf8_bin NOT NULL DEFAULT 'jpg',
  UPLOADER bigint(20) unsigned NOT NULL,
  WIDTH int(10) NOT NULL DEFAULT 0,
  HEIGHT int(10) NOT NULL DEFAULT 0,
  DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TAGS varchar(1000) DEFAULT 'tagme',
  RATE tinyint(4) NOT NULL DEFAULT 0,
  FLAGCOUNT int(10) unsigned DEFAULT 0,
  PRIMARY KEY (ID),
  FOREIGN KEY (UPLOADER) REFERENCES @tpusers (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE @tpcomments (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  REL bigint(20) unsigned NOT NULL,
  OWNER bigint(20) unsigned NOT NULL,
  CONTENT varchar(1500) NOT NULL DEFAULT '[Bad Comment]',
  FLAGCOUNT int(10) unsigned DEFAULT 0,
  PRIMARY KEY (ID),
  FOREIGN KEY (OWNER) REFERENCES @tpusers (ID),
  FOREIGN KEY (REL) REFERENCES @tpimages (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE @tploginattempts (
  IP varchar(15) UNIQUE NOT NULL,
  PROXY varchar(15) UNIQUE NOT NULL,
  DATE  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TRIES int(12) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE @tpipban (
  IP varchar(15) UNIQUE NOT NULL,
  PROXY varchar(15) UNIQUE NOT NULL,
  DATE  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  BANCOUNT int(12) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;